import type { Project } from '@/types'

export function exportWpTheme(project: Project) {
  const themeName = project.meta.title.replace(/[^a-z0-9]/gi, '-').toLowerCase() || 'sage-theme'
  const css = project.customCss || ''
  const js = project.customJs || ''
  const body = renderNodeToHtml(project.root)

  const files: Record<string, string> = {
    [`${themeName}/style.css`]: `/*
Theme Name: ${escapeHtml(project.meta.title || 'SAGE Theme')}
Author: ${escapeHtml(project.meta.author || 'SAGE')}
Description: ${escapeHtml(project.meta.description || 'Generated by SAGE Builder')}
Version: 1.0.0
*/
${css}`,
    [`${themeName}/functions.php`]: `<?php
add_action('wp_enqueue_scripts', function () {
  wp_enqueue_style('${themeName}-style', get_stylesheet_uri());
  wp_enqueue_script('${themeName}-script', get_template_directory_uri() . '/main.js', [], '1.0', true);
});
`,
    [`${themeName}/index.php`]: generateIndex(themeName, body, css, js),
    [`${themeName}/header.php`]: generateHeader(themeName),
    [`${themeName}/footer.php`]: generateFooter(),
    [`${themeName}/front-page.php`]: generateFrontPage(themeName, body, css, js),
    [`${themeName}/single.php`]: generateSingle(themeName),
    [`${themeName}/page.php`]: generatePage(themeName),
    [`${themeName}/archive.php`]: generateArchive(themeName),
    [`${themeName}/search.php`]: generateSearch(themeName),
    [`${themeName}/main.js`]: js,
  }

  return { name: themeName, files }
}

function generateIndex(_theme: string, body: string, css: string, js: string) {
  return `<!DOCTYPE html>
<html ${getLanguageAttributes()}>
<head>
<meta charset="UTF-8" />
<meta name="viewport" content="width=device-width, initial-scale=1.0" />
<title><?php wp_title('|', true, 'right'); ?></title>
<?php wp_head(); ?>
<style>${css}</style>
</head>
<body>
<header role="banner"><?php wp_body_open(); ?></header>
<div id="root">
${body}
</div>
<?php wp_footer(); ?>
<script>${js}</script>
</body>
</html>
`
}

function generateHeader(_theme: string) {
  return `<!DOCTYPE html>
<html ${getLanguageAttributes()}>
<head>
<meta charset="UTF-8" />
<meta name="viewport" content="width=device-width, initial-scale=1.0" />
<title><?php wp_title('|', true, 'right'); ?></title>
<?php wp_head(); ?>
</head>
<body>
  <header class="sage-header">
  <h1><?php bloginfo('name'); ?></h1>
  <?php wp_nav_menu(['theme_location' => 'primary']); ?>
</header>
`
}

function generateFooter() {
  return `<footer class="sage-footer">
  <p>&copy; <?php echo date('Y'); ?> <?php bloginfo('name'); ?></p>
</footer>
<?php wp_footer(); ?>
</body>
</html>
`
}

function generateFrontPage(_theme: string, body: string, css: string, js: string) {
  return generateIndex(_theme, body, css, js)
}

function generateSingle(_theme: string) {
  return `<!DOCTYPE html>
<html ${getLanguageAttributes()}>
<head>
<meta charset="UTF-8" />
<meta name="viewport" content="width=device-width, initial-scale=1.0" />
<title><?php wp_title('|', true, 'right'); ?></title>
<?php wp_head(); ?>
</head>
<body>
  <header class="sage-header">
  <h1><a href="<?php echo home_url('/'); ?>"><?php bloginfo('name'); ?></a></h1>
</header>
<main>
  <?php while (have_posts()) : the_post(); ?>
    <article>
      <h2><?php the_title(); ?></h2>
      <div><?php the_content(); ?></div>
    </article>
  <?php endwhile; ?>
</main>
<?php get_footer(); ?>
`
}

function generatePage(_theme: string) {
  return `<!DOCTYPE html>
<html ${getLanguageAttributes()}>
<head>
<meta charset="UTF-8" />
<meta name="viewport" content="width=device-width, initial-scale=1.0" />
<title><?php wp_title('|', true, 'right'); ?></title>
<?php wp_head(); ?>
</head>
<body>
  <header class="sage-header">
  <h1><a href="<?php echo home_url('/'); ?>"><?php bloginfo('name'); ?></a></h1>
</header>
<main>
  <?php while (have_posts()) : the_post(); ?>
    <article>
      <h2><?php the_title(); ?></h2>
      <div><?php the_content(); ?></div>
    </article>
  <?php endwhile; ?>
</main>
<?php get_footer(); ?>
`
}

function generateArchive(_theme: string) {
  return `<!DOCTYPE html>
<html ${getLanguageAttributes()}>
<head>
<meta charset="UTF-8" />
<meta name="viewport" content="width=device-width, initial-scale=1.0" />
<title><?php wp_title('|', true, 'right'); ?></title>
<?php wp_head(); ?>
</head>
<body>
  <header class="sage-header">
  <h1><a href="<?php echo home_url('/'); ?>"><?php bloginfo('name'); ?></a></h1>
</header>
<main>
  <h2>Archive</h2>
  <?php if (have_posts()) : while (have_posts()) : the_post(); ?>
    <article>
      <h3><a href="<?php the_permalink(); ?>"><?php the_title(); ?></a></h3>
    </article>
  <?php endwhile; endif; ?>
</main>
<?php get_footer(); ?>
`
}

function generateSearch(_theme: string) {
  return `<!DOCTYPE html>
<html ${getLanguageAttributes()}>
<head>
<meta charset="UTF-8" />
<meta name="viewport" content="width=device-width, initial-scale=1.0" />
<title><?php wp_title('|', true, 'right'); ?></title>
<?php wp_head(); ?>
</head>
<body>
  <header class="sage-header">
  <h1><a href="<?php echo home_url('/'); ?>"><?php bloginfo('name'); ?></a></h1>
</header>
<main>
  <h2>Search Results</h2>
  <?php if (have_posts()) : while (have_posts()) : the_post(); ?>
    <article>
      <h3><a href="<?php the_permalink(); ?>"><?php the_title(); ?></a></h3>
    </article>
  <?php endwhile; endif; ?>
</main>
<?php get_footer(); ?>
`
}

function renderNodeToHtml(node: any): string {
  if (!node) return ''
  if (node.type === 'text') {
    return `<div>${escapeHtml(String(node.props?.content || ''))}</div>`
  }
  if (node.type === 'image') {
    return `<img src="${escapeHtml(String(node.props?.src || ''))}" alt="${escapeHtml(String(node.props?.alt || ''))}" />`
  }
  if (node.type === 'button') {
    return `<a href="${escapeHtml(String(node.props?.href || '#'))}">${escapeHtml(String(node.props?.label || ''))}</a>`
  }
  if (node.type === 'video') {
    return `<video src="${escapeHtml(String(node.props?.src || ''))}" ${node.props?.controls ? 'controls' : ''}></video>`
  }
  if (node.type === 'divider') {
    return `<hr style="border: ${node.props?.thickness || '1px'} ${node.props?.style || 'solid'} ${node.props?.color || '#ccc'};" />`
  }
  if (node.type === 'spacer') {
    return `<div style="height: ${node.props?.height || '40px'};"></div>`
  }
  if (node.type === 'html') {
    return String(node.props?.code || '')
  }
  const children = (node.children || []).map(renderNodeToHtml).join('\n')
  const style = Object.entries(node.styles || {})
    .filter(([, v]) => v)
    .map(([k, v]) => `${camelToKebab(k)}: ${v}`)
    .join('; ')
  return `<div${style ? ` style="${style}"` : ''}>\n${children}\n</div>`
}

function getLanguageAttributes() {
  return '<?php language_attributes(); ?>'
}

function escapeHtml(str: string) {
  return str
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;')
    .replace(/'/g, '&#39;')
}

function camelToKebab(str: string) {
  return str.replace(/([a-z0-9])([A-Z])/g, '$1-$2').toLowerCase()
}
